-- MySQL Script generated by MySQL Workbench
-- Mon Jun 25 19:56:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';


-- -----------------------------------------------------
-- Schema websecure
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `websecure` ;

-- -----------------------------------------------------
-- Schema websecure
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `websecure` DEFAULT CHARACTER SET utf8mb4 ;
USE `websecure` ;

-- -----------------------------------------------------
-- Create user (specified in application.properties)
-- -----------------------------------------------------
DROP USER IF EXISTS 'kaas'@'localhost';
CREATE USER 'webuser'@'localhost' IDENTIFIED BY 'webpasswd';
GRANT ALL PRIVILEGES ON websecure.* TO 'webuser'@'localhost' WITH GRANT OPTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

